In [12]:
import numpy as np
import pandas as pd

df=pd.read_csv('Purchased_Dataset.csv')
print(df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617

In [13]:
X=df.iloc[:,1:4].values
y=df.iloc[:,4].values
print(X)


[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]


In [17]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
label1=LabelEncoder()
X[:,0]=label1.fit_transform(X[:,0])
print(X)

[[1 1 19000]
 [1 17 20000]
 [0 8 43000]
 ...
 [0 32 20000]
 [1 18 33000]
 [0 31 36000]]


In [18]:
import xgboost
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
clf=xgboost.XGBClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))

[[55  3]
 [ 1 21]]


In [23]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=7)
knnclassifier= KNeighborsClassifier(n_neighbors=5)
knnclassifier.fit(X_train,y_train)
y_pred=knnclassifier.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

0.825